name: All Tests
on:
  # Roda quando você sobe código
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Roda Manualmente (botão "Run workflow") - Muito útil!
  workflow_dispatch:

  # Roda Automaticamente (Cron Job)
  #schedule:
  # Exemplo: Roda todo dia às 09:00 UTC (06:00 da manhã no Brasil)
  # Sintaxe: 'minuto hora dia mês dia_da_semana'
  # - cron: '0 9 * * *'

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código
      - uses: actions/checkout@v4

      # 2. Instala o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: npm ci

      # 4. Roda os testes!
      - name: Run Playwright tests
        run: npx playwright test

      # 5. Salva o relatório e o Trace como "Artefato"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
